# Our global, build settings
[build]
   base    = "client"        # run the build from this directory
   command = "npm run build"
   publish = "dist"      # the output diretory to push to the CDN after the build
command = "gulp build" # the command to build our site