# Our global, build settings
[build]
   base    = "client"        # run the build from this directory
   command = "npm run build"
   publish = "client/dist"      # the output diretory to push to the CDN after the build